apiVersion: v1
kind: Namespace
metadata:
  name: o11y-lab
  labels:
    name: o11y-lab
    monitoring: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: observability
  labels:
    name: observability
    purpose: monitoring
