apiVersion: v1
kind: ConfigMap
metadata:
  name: service-a-config
  namespace: o11y-lab
data:
  SERVICE_B_URL: "http://service-b.o11y-lab.svc.cluster.local:8002"
  SERVICE_D_URL: "http://service-d.o11y-lab.svc.cluster.local:8004"
  THIRD_PARTY_API: "https://api.github.com/zen"
  OTEL_COLLECTOR_ENDPOINT: "otel-collector.observability.svc.cluster.local:4317"
  DB_HOST: "postgres.o11y-lab.svc.cluster.local"
  DB_PORT: "5432"
  DB_NAME: "o11ylab"
  DB_USER: "postgres"

---
apiVersion: v1
kind: Secret
metadata:
  name: service-a-secret
  namespace: o11y-lab
type: Opaque
stringData:
  DB_PASSWORD: "postgres"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-a
  namespace: o11y-lab
  labels:
    app: service-a
spec:
  replicas: 2
  selector:
    matchLabels:
      app: service-a
  template:
    metadata:
      labels:
        app: service-a
      annotations:
        # 启用 OpenTelemetry 自动埋点
        instrumentation.opentelemetry.io/inject-python: "true"
    spec:
      containers:
        - name: service-a
          image: service-a:latest  # 在实际环境中使用完整的镜像地址
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8001
              name: http
          envFrom:
            - configMapRef:
                name: service-a-config
            - secretRef:
                name: service-a-secret
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /health
              port: 8001
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8001
            initialDelaySeconds: 10
            periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: service-a
  namespace: o11y-lab
  labels:
    app: service-a
spec:
  selector:
    app: service-a
  ports:
    - port: 8001
      targetPort: 8001
      protocol: TCP
      name: http
  type: ClusterIP
